// `doctor` checks. Each check reports `{ name, ok, severity, detail, hint?,
// skipped? }`; the overall result is `ok` only when no error-severity check
// failed. Remote checks degrade to `skipped` when `gh` is unavailable or
// `--no-remote` is passed, and the caller is told how many were skipped rather
// than being told everything was verified.

import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { spawnSync } from 'node:child_process';
import { CONFIG_FILE, TOOL_NAME } from './constants.mjs';
import { buildConfig, readConfig, validateConfig } from './config.mjs';
import { renderCaller, renderStandalone } from './render.mjs';
import { gitRoot, repoSlug } from './repo.mjs';
import { VERSION } from './package-info.mjs';

const ERROR = 'error';
const WARNING = 'warning';

function check(name, ok, severity, detail, extra = {}) {
  return { name, ok, severity, detail, ...extra };
}

function ghAvailable() {
  const result = spawnSync('gh', ['--version'], { encoding: 'utf8' });
  return result.status === 0;
}

function ghJson(args) {
  const result = spawnSync('gh', args, { encoding: 'utf8' });
  if (result.status !== 0) {
    return { ok: false, error: (result.stderr || result.stdout || 'gh failed').trim() };
  }
  try {
    return { ok: true, value: JSON.parse(result.stdout) };
  } catch (error) {
    return { ok: false, error: `could not parse gh output: ${error.message}` };
  }
}

/**
 * @param {object} args
 * @param {string} args.dir directory to check (resolved to its git root)
 * @param {object} [args.flags] CLI flags, merged over the stored config
 * @param {boolean} [args.noRemote] skip every `gh` check
 * @returns {{ ok: boolean, dir: string|null, checks: object[], skipped: number }}
 */
export function runChecks({ dir, flags = {}, noRemote = false }) {
  const checks = [];
  const root = gitRoot(dir);

  if (!root) {
    checks.push(check('repo', false, ERROR, `${dir} is not inside a git work tree`, {
      hint: 'run this in a checkout, or pass --repo',
    }));
    return { ok: false, dir: null, checks, skipped: 0 };
  }

  const slug = repoSlug(root);
  checks.push(
    slug
      ? check('remote', true, ERROR, `origin is ${slug.slug}`)
      : check('remote', false, ERROR, 'no parseable GitHub "origin" remote', {
          hint: 'add a GitHub remote, e.g. git remote add origin git@github.com:owner/repo.git',
        }),
  );

  const existing = readConfig(root);
  if (existing === null) {
    checks.push(check('config', false, ERROR, `${CONFIG_FILE} not found`, {
      hint: 'run "mention-agent setup" in this repository',
    }));
    return { ok: false, dir: root, checks, skipped: 0 };
  }

  let config;
  let configError = null;
  try {
    config = buildConfig({ existing, flags });
    configError = validateConfig(config).join('; ') || null;
  } catch (error) {
    configError = error.message;
  }
  checks.push(
    configError
      ? check('config', false, ERROR, configError)
      : check('config', true, ERROR, 'config is valid'),
  );
  if (configError) {
    return { ok: false, dir: root, checks, skipped: 0 };
  }

  const workflowPath = join(root, config.workflow.path);
  checks.push(
    existsSync(workflowPath)
      ? check('workflow', true, ERROR, `${config.workflow.path} exists`)
      : check('workflow', false, ERROR, `${config.workflow.path} not found`, {
          hint: 'run "mention-agent update"',
        }),
  );

  if (existsSync(workflowPath)) {
    const expected = (config.standalone ? renderStandalone : renderCaller)(config);
    const actual = readFileSync(workflowPath, 'utf8');
    // The first line is a version marker; compare the rest so a tool version
    // bump alone does not read as a hand edit.
    const body = (text) => text.split('\n').slice(1).join('\n').trim();
    const current = body(actual) === body(expected);
    checks.push(
      current
        ? check('workflow-current', true, ERROR, 'workflow matches the config')
        : check('workflow-current', false, ERROR, 'workflow does not match the config', {
            hint: 'run "mention-agent update" to regenerate it',
          }),
    );

    const markerVersion = (actual.match(/^# generated by mention-agent v(\S+)/m) || [])[1] || null;
    checks.push(
      markerVersion === VERSION
        ? check('workflow-version', true, WARNING, `generated by ${TOOL_NAME} v${VERSION}`)
        : check('workflow-version', false, WARNING, markerVersion ? `generated by v${markerVersion}; this tool is v${VERSION}` : 'no version marker', {
            hint: 'run "mention-agent update"',
          }),
    );
  }

  checks.push(
    config.allowUsers.length > 0
      ? check('allowlist', true, ERROR, `restricted to ${config.allowUsers.join(', ')}`)
      : check('allowlist', false, ERROR, 'no allowlist: any user with write access can trigger a run', {
          hint: 'set --allow-users to keep token spend to named people',
        }),
  );

  checks.push(
    config.selfLogin
      ? check('self-loop', true, WARNING, `ignoring comments from ${config.selfLogin}`)
      : check('self-loop', false, WARNING, 'no self-login set: the agent could answer its own comments', {
          hint: 'set --self-login to the account the token belongs to',
        }),
  );

  checks.push(
    config.share
      ? check('share', false, WARNING, 'session sharing is enabled')
      : check('share', true, WARNING, 'session sharing is disabled'),
  );

  const skipped = runRemoteChecks(checks, { slug: slug?.slug ?? null, config, noRemote });
  const ok = checks.every((entry) => entry.ok || entry.severity !== ERROR);
  return { ok, dir: root, checks, skipped };
}

function runRemoteChecks(checks, { slug, config, noRemote }) {
  const wantRemote = !noRemote && slug;
  if (!wantRemote) {
    checks.push(check('secrets', true, ERROR, 'skipped (no remote check)', { skipped: true }));
    checks.push(check('actions', true, ERROR, 'skipped (no remote check)', { skipped: true }));
    return 2;
  }
  if (!ghAvailable()) {
    checks.push(check('secrets', true, ERROR, 'skipped (gh not installed)', { skipped: true }));
    checks.push(check('actions', true, ERROR, 'skipped (gh not installed)', { skipped: true }));
    return 2;
  }

  let skipped = 0;

  const required = [config.provider.secret];
  if (config.identity === 'pat') required.push(config.tokenSecret);
  const secrets = ghJson(['api', `repos/${slug}/actions/secrets`, '--jq', '[.secrets[].name]']);
  if (!secrets.ok) {
    checks.push(check('secrets', true, ERROR, `skipped (${secrets.error})`, { skipped: true }));
    skipped += 1;
  } else {
    const missing = required.filter((name) => !secrets.value.includes(name));
    checks.push(
      missing.length === 0
        ? check('secrets', true, ERROR, `repository secrets present: ${required.join(', ')}`)
        : check('secrets', false, ERROR, `missing repository secrets: ${missing.join(', ')}`, {
            hint: 'add them under Settings → Secrets and variables → Actions',
          }),
    );
  }

  const actions = ghJson(['api', `repos/${slug}/actions/permissions`, '--jq', '.enabled']);
  if (!actions.ok) {
    checks.push(check('actions', true, ERROR, `skipped (${actions.error})`, { skipped: true }));
    skipped += 1;
  } else {
    checks.push(
      actions.value === true
        ? check('actions', true, ERROR, 'GitHub Actions is enabled')
        : check('actions', false, ERROR, 'GitHub Actions is disabled for this repository'),
    );
  }

  return skipped;
}
