// Version-independent names shared across the CLI, the renderers, and the
// reusable workflow. Nothing here is deployment-specific: the repository that
// hosts the reusable workflow is resolved from package metadata at runtime, and
// the mention phrase and secret names come from the user's config or flags.

export const TOOL_NAME = 'mention-agent';

// Target-repository files written by `setup`.
export const CONFIG_FILE = '.mention-agent.json';
export const WORKFLOW_DIR = '.github/workflows';
export const WORKFLOW_FILE = `${TOOL_NAME}.yml`;

// A moving tag the release workflow force-updates on every release, so target
// repositories can point their caller at `@<TOOL_NAME>-v1` and pick up
// compatible updates without editing each repo.
export const VERSION_REF = `${TOOL_NAME}-v1`;

// Generic defaults; nothing project-specific is baked in.
export const DEFAULT_TOKEN_SECRET = 'MENTION_AGENT_TOKEN';
export const DEFAULT_AGENT = 'build';

// Third-party actions invoked by the generated workflow. The reusable workflow
// is the single place these are named, so target repositories never carry them.
// The agent action is pinned to a reviewed commit so a moved tag cannot change
// code that runs with a consumer's token; bump it deliberately.
export const CHECKOUT_ACTION = 'actions/checkout@v4';
export const AGENT_ACTION = 'anomalyco/opencode/github@77fc88c8ade8e5a620ebbe1197f3a572d29ae91a';
export const AGENT_ACTION_NOTE = 'github-v1.2.19';

// First line of every generated file. `doctor` uses it to detect stale copies.
export const GENERATED_MARKER = `# generated by ${TOOL_NAME}`;
