// Version-independent names shared across the CLI, the renderers, and the
// reusable workflow. Nothing here is deployment-specific: the repository that
// hosts the reusable workflow is resolved from package metadata at runtime, and
// the mention phrase and secret names come from the user's config or flags.

export const TOOL_NAME = 'mention-agent';

// Target-repository files written by `setup`.
export const CONFIG_FILE = '.mention-agent.json';
export const WORKFLOW_DIR = '.github/workflows';
export const WORKFLOW_FILE = `${TOOL_NAME}.yml`;

// Generic defaults; nothing project-specific is baked in.
export const DEFAULT_TOKEN_SECRET = 'MENTION_AGENT_TOKEN';
export const DEFAULT_AGENT = 'build';

// The restricted agent injected at run time (Lever 1). It is defined in a config
// file the workflow writes before the agent action runs, so the repository's own
// local default is untouched.
export const RESTRICTED_AGENT = 'mention-agent';

// Third-party actions invoked by the generated workflow. The reusable workflow
// is the single place these are named, so target repositories never carry them.
// The agent action is pinned to a reviewed commit so a moved tag cannot change
// code that runs with a consumer's token; bump it deliberately.
// actions/checkout v4.2.2. Keep this pinned to a reviewed commit; a moving
// action tag would execute new third-party code in every consumer repository.
export const CHECKOUT_ACTION = 'actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683';
export const AGENT_ACTION = 'anomalyco/opencode/github@77fc88c8ade8e5a620ebbe1197f3a572d29ae91a';
export const AGENT_ACTION_NOTE = 'github-v1.2.19';

// First line of every generated file. `doctor` uses it to detect stale copies.
export const GENERATED_MARKER = `# generated by ${TOOL_NAME}`;
