// session-search Pi extension. Generated by `session-search install`, which
// substitutes __SESSION_SEARCH_NODE__ (and optionally __SESSION_SEARCH_CACHE__).
//
// Registers the MCP server for the session, refreshes the index after a run
// settles, exposes a /history command, warns when a third-party extension has
// replaced built-in MCP, and can require an interactive confirmation gate.
import type { ExtensionAPI } from '@earendil-works/pi-coding-agent';

const NODE = '__SESSION_SEARCH_NODE__';
const CLI = '__SESSION_SEARCH_BIN__';
const CACHE = '__SESSION_SEARCH_CACHE__';
const SERVER_NAME = 'session_search';

export default function sessionSearch(pi: ExtensionAPI): void {
  const cacheArgs = CACHE ? ['--cache', CACHE] : [];

  pi.on('session_start', (_event, ctx) => {
    pi.registerMcpServer(SERVER_NAME, {
      command: NODE,
      args: [CLI, 'mcp', ...cacheArgs],
      cwd: ctx.cwd,
      exposure: 'direct',
      description: 'Search local coding-agent session history',
      env: CACHE ? { SESSION_SEARCH_CACHE: CACHE } : {},
    });

    // Built-in MCP can be replaced by a third-party extension; if so, our
    // registration will not connect and the model never sees the tools.
    const servers = pi.getMcpServers?.();
    if (Array.isArray(servers) && !servers.some((server) => server.name === SERVER_NAME)) {
      ctx.ui.notify(
        'session-search: MCP server not registered (another MCP extension may have replaced built-in MCP); use `session-search install --print`',
        'warning',
      );
    }
  });

  pi.on('agent_settled', (_event, ctx) => {
    const sessionDir = ctx.sessionManager?.getSessionDir?.();
    const sessionArgs = sessionDir ? ['--pi-sessions', sessionDir] : [];
    void pi.exec(NODE, [CLI, 'index', '--project', ctx.cwd, ...sessionArgs, ...cacheArgs], {
      cwd: ctx.cwd,
      timeout: 60_000,
    });
  });

  // Fail-safe gate: the tools are read-only, but an unattended run can require
  // an interactive confirmation with SESSION_SEARCH_REQUIRE_UI=1.
  pi.on('tool_call', (event, ctx) => {
    const isOurs =
      event.toolName === 'history_search' ||
      event.toolName === 'history_show' ||
      event.toolName.startsWith(`mcp__${SERVER_NAME}__`);
    if (!isOurs) return undefined;
    if (process.env.SESSION_SEARCH_REQUIRE_UI === '1' && !ctx.hasUI) {
      return { block: true, reason: 'session-search: interactive confirmation required' };
    }
    return undefined;
  });

  pi.registerCommand('history', {
    description: 'Search past sessions',
    handler: async (input, ctx) => {
      const result = await pi.exec(NODE, [CLI, 'search', input, ...cacheArgs], {
        cwd: ctx.cwd,
        timeout: 30_000,
      });
      ctx.ui.notify(result.stdout.trim() || '(no matches)', result.code === 0 ? 'info' : 'error');
    },
  });
}
