// session-search Pi extension. Generated by `session-search install`, which
// substitutes __SESSION_SEARCH_BIN__ (and optionally __SESSION_SEARCH_CACHE__).
//
// Registers the MCP server for the session, refreshes the index after a run
// settles, and exposes a /history command. Pi loads TypeScript directly.
import type { ExtensionAPI } from '@earendil-works/pi-coding-agent';

const NODE = '__SESSION_SEARCH_NODE__';
const CLI = '__SESSION_SEARCH_BIN__';
const CACHE = '__SESSION_SEARCH_CACHE__';

export default function sessionSearch(pi: ExtensionAPI): void {
  const cacheArgs = CACHE ? ['--cache', CACHE] : [];

  pi.on('session_start', (_event, ctx) => {
    pi.registerMcpServer('session_search', {
      command: NODE,
      args: [CLI, 'mcp', ...cacheArgs],
      cwd: ctx.cwd,
      exposure: 'direct',
      description: 'Search local coding-agent session history',
      env: CACHE ? { SESSION_SEARCH_CACHE: CACHE } : {},
    });
  });

  pi.on('agent_settled', (_event, ctx) => {
    void pi.exec(NODE, [CLI, 'index', '--project', ctx.cwd, ...cacheArgs], {
      cwd: ctx.cwd,
      timeout: 60_000,
    });
  });

  pi.registerCommand('history', {
    description: 'Search past sessions',
    handler: async (input, ctx) => {
      const result = await pi.exec(NODE, [CLI, 'search', input, ...cacheArgs], {
        cwd: ctx.cwd,
        timeout: 30_000,
      });
      ctx.ui.notify(result.stdout.trim() || '(no matches)', result.code === 0 ? 'info' : 'error');
    },
  });
}
