import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readdirSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { buildConfig } from '../lib/config.mjs';
import { renderCaller, renderReusable, renderStandalone } from '../lib/render.mjs';
import { REPOSITORY, VERSION } from '../lib/package-info.mjs';

const packageRoot = fileURLToPath(new URL('..', import.meta.url));
const reusableFile = fileURLToPath(new URL('../../.github/workflows/mention-agent.yml', import.meta.url));

function config(flags = {}) {
  return buildConfig({
    flags: { mention: '@example-bot', allowUsers: ['alice', 'bob'], ...flags },
  });
}

test('renderCaller produces a caller for the shared workflow', () => {
  const yaml = renderCaller(config());
  assert.match(yaml, /^# generated by mention-agent v/m);
  assert.match(yaml, /issue_comment:/);
  assert.match(yaml, /pull_request_review_comment:/);
  assert.match(yaml, /uses: ".*\/\.github\/workflows\/mention-agent\.yml@mention-agent-v1"/);
  assert.match(yaml, /mention: "@example-bot"/);
  assert.ok(yaml.includes('allow-users: "[\\"alice\\",\\"bob\\"]"'), 'caller passes the allowlist as a JSON array');
  assert.match(yaml, /self-login: "example-bot"/);
  assert.match(yaml, /share: false/);
  assert.match(yaml, /token: \$\{\{ secrets\.MENTION_AGENT_TOKEN \}\}/);
  assert.match(yaml, /provider-key: \$\{\{ secrets\.OPENCODE_API_KEY \}\}/);
});

test('renderCaller in app mode drops the token and grants id-token', () => {
  const yaml = renderCaller(config({ identity: 'app' }));
  assert.match(yaml, /id-token: write/);
  assert.doesNotMatch(yaml, /secrets\.MENTION_AGENT_TOKEN/);
  assert.match(yaml, /provider-key: \$\{\{ secrets\.OPENCODE_API_KEY \}\}/);
});

test('renderStandalone inlines the gate and the steps', () => {
  const yaml = renderStandalone(config({ standalone: true }));
  assert.match(yaml, /use_github_token: true/);
  assert.match(yaml, /actions\/checkout@v4/);
  assert.match(yaml, /anomalyco\/opencode\/github@latest/);
  assert.ok(
    yaml.includes(`contains(fromJSON("[\\"alice\\",\\"bob\\"]"), github.event.comment.user.login)`),
    'standalone gate matches the allowlist through fromJSON',
  );
  assert.match(yaml, /github\.event\.comment\.user\.login != "example-bot"/);
  assert.doesNotMatch(yaml, /uses: .*mention-agent\.yml@/);
});

test('renderStandalone omits the allowlist clause when no users are set', () => {
  const yaml = renderStandalone(buildConfig({ flags: { mention: '@example-bot', allowUsers: [] } }));
  assert.doesNotMatch(yaml, /allow-users/);
  assert.doesNotMatch(yaml, /fromJSON/);
});

test('a caller with no allowlist passes an empty string', () => {
  const yaml = renderCaller(buildConfig({ flags: { mention: '@example-bot', allowUsers: [] } }));
  assert.match(yaml, /allow-users: ""/);
});

test('renderReusable is a workflow_call with the expected gate and secrets', () => {
  const yaml = renderReusable();
  assert.match(yaml, /workflow_call:/);
  assert.match(yaml, /provider-key:/);
  assert.match(yaml, /contains\(github\.event\.comment\.body, inputs\.mention\)/);
  assert.match(yaml, /inputs\['allow-users'\]/);
  assert.match(yaml, /fromJSON\(inputs\['allow-users'\]\)/);
  assert.doesNotMatch(yaml, /replace\(/, 'GitHub expressions have no replace function');
  assert.match(yaml, /use_github_token: \$\{\{ inputs\.identity == 'pat' \}\}/);
  assert.match(yaml, /Export the provider credential/);
  assert.match(yaml, /GITHUB_ENV/);
  assert.equal(VERSION, readFileSync(`${packageRoot}/package.json`, 'utf8').match(/"version": "([^"]+)"/)[1]);
});

test('the committed reusable workflow matches the renderer', () => {
  assert.equal(readFileSync(reusableFile, 'utf8'), renderReusable());
});

test('no account name or credential is hardcoded in source', () => {
  const files = [
    `${packageRoot}/bin/mention-agent.mjs`,
    ...readdirSync(`${packageRoot}/lib`).map((name) => `${packageRoot}/lib/${name}`),
    ...readdirSync(`${packageRoot}/scripts`).map((name) => `${packageRoot}/scripts/${name}`),
  ];
  for (const file of files) {
    const text = readFileSync(file, 'utf8');
    assert.doesNotMatch(text, /faetschi/i, `hardcoded account name in ${file}`);
    assert.doesNotMatch(text, /github_pat_|ghp_[A-Za-z0-9]{20,}/, `hardcoded token in ${file}`);
  }
});

test('the hosting repository is derived from package metadata', () => {
  assert.equal(REPOSITORY, 'faetschi-bot/faetschi-bot-utils');
  assert.equal(config().workflow.reusableRepo, REPOSITORY);
  // The renderer output carries the derived repo only through config, never a literal.
  assert.doesNotMatch(renderReusable(), /faetschi/i);
});
