import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readdirSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { ConfigError, buildConfig, validateConfig, wantsStandalone } from '../lib/config.mjs';
import { securityChecklist } from '../lib/checklist.mjs';
import { renderCaller, renderReusable, renderStandalone } from '../lib/render.mjs';
import { REPOSITORY, VERSION } from '../lib/package-info.mjs';

const packageRoot = fileURLToPath(new URL('..', import.meta.url));
const reusableFile = fileURLToPath(new URL('../../.github/workflows/mention-agent.yml', import.meta.url));

function config(flags = {}) {
  return buildConfig({
    flags: { mention: '@example-bot', allowUsers: ['alice', 'bob'], ...flags },
  });
}

test('renderCaller produces a caller for the shared workflow', () => {
  const yaml = renderCaller(config());
  assert.match(yaml, /^# generated by mention-agent v/m);
  assert.match(yaml, /issue_comment:/);
  assert.match(yaml, /pull_request_review_comment:/);
  assert.match(yaml, /uses: ".*\/\.github\/workflows\/mention-agent\.yml@mention-agent-v0\.1\.0"/);
  assert.match(yaml, /mention: "@example-bot"/);
  assert.ok(yaml.includes('allow-users: "[\\"alice\\",\\"bob\\"]"'), 'caller passes the allowlist as a JSON array');
  assert.match(yaml, /self-login: "example-bot"/);
  assert.match(yaml, /allow-writes: false/);
  assert.match(yaml, /share: false/);
  assert.match(yaml, /token: \$\{\{ secrets\.MENTION_AGENT_TOKEN \}\}/);
  assert.match(yaml, /provider-key: \$\{\{ secrets\.OPENCODE_API_KEY \}\}/);
});

test('renderCaller in app mode drops the token and grants id-token', () => {
  const yaml = renderCaller(config({ identity: 'app' }));
  assert.match(yaml, /id-token: write/);
  assert.doesNotMatch(yaml, /secrets\.MENTION_AGENT_TOKEN/);
  assert.match(yaml, /provider-key: \$\{\{ secrets\.OPENCODE_API_KEY \}\}/);
});

test('renderStandalone inlines the gate and the steps', () => {
  const yaml = renderStandalone(config({ standalone: true }));
  assert.match(yaml, /use_github_token: true/);
  assert.match(yaml, /actions\/checkout@[0-9a-f]{40}/);
  assert.match(yaml, /uses: anomalyco\/opencode\/github@[0-9a-f]{40} # /);
  assert.match(yaml, /persist-credentials: false/);
  assert.match(yaml, /timeout-minutes: 30/);
  assert.match(yaml, /group: mention-agent-\$\{\{ github\.event\.issue\.number \|\| github\.event\.pull_request\.number \}\}/);
  // GitHub expressions only accept single-quoted string literals.
  assert.ok(yaml.includes(`contains(github.event.comment.body, '@example-bot')`), 'mention is a single-quoted literal');
  assert.ok(yaml.includes(`contains(fromJSON('["OWNER","MEMBER","COLLABORATOR"]'), github.event.comment.author_association)`), 'association gate');
  assert.ok(yaml.includes(`contains(fromJSON('["alice","bob"]'), github.event.comment.user.login)`), 'allowlist via fromJSON');
  assert.match(yaml, /github\.event\.pull_request\.head\.repo\.fork == false/);
  assert.match(yaml, /name: Reject fork pull requests/);
  assert.ok(yaml.includes(`github.event.comment.user.login != 'example-bot'`), 'self-login is a single-quoted literal');
  assert.doesNotMatch(yaml, /uses: .*mention-agent\.yml@/);
  assert.equal((yaml.match(/"/g) || []).length > 0, true, 'YAML still quotes values');
});

test('renderStandalone in app mode uses the default token for checkout only', () => {
  const yaml = renderStandalone(config({ identity: 'app' }));
  assert.match(yaml, /use_github_token: false/);
  assert.match(yaml, /token: \$\{\{ github\.token \}\}/);
  assert.doesNotMatch(yaml, /name: Verify token/);
});

test('renderStandalone omits the allowlist clause when no users are set', () => {
  const yaml = renderStandalone(buildConfig({ flags: { mention: '@example-bot', allowUsers: [] } }));
  assert.doesNotMatch(yaml, /allow-users/);
  assert.doesNotMatch(yaml, /alice/);
});

test('a caller with no allowlist passes an empty string', () => {
  const yaml = renderCaller(buildConfig({ flags: { mention: '@example-bot', allowUsers: [] } }));
  assert.match(yaml, /allow-users: ""/);
});

test('renderReusable is a workflow_call with the expected gate and secrets', () => {
  const yaml = renderReusable();
  assert.match(yaml, /workflow_call:/);
  assert.match(yaml, /provider-key:/);
  assert.match(yaml, /contains\(github\.event\.comment\.body, inputs\.mention\)/);
  assert.ok(yaml.includes(`contains(fromJSON('["OWNER","MEMBER","COLLABORATOR"]'), github.event.comment.author_association)`), 'association gate');
  assert.match(yaml, /inputs\['allow-users'\]/);
  assert.match(yaml, /fromJSON\(inputs\['allow-users'\]\)/);
  assert.doesNotMatch(yaml, /replace\(/, 'GitHub expressions have no replace function');
  assert.match(yaml, /persist-credentials: \$\{\{ inputs\.allow-writes \}\}/);
  assert.match(yaml, /allow-writes:/);
  assert.match(yaml, /timeout-minutes: 30/);
  assert.match(yaml, /uses: anomalyco\/opencode\/github@[0-9a-f]{40} # /);
  assert.match(yaml, /actions\/checkout@[0-9a-f]{40}/);
  assert.match(yaml, /github\.event\.pull_request\.head\.repo\.fork == false/);
  assert.match(yaml, /use_github_token: \$\{\{ inputs\.identity == 'pat' \}\}/);
  assert.match(yaml, /Export the provider credential/);
  assert.match(yaml, /GITHUB_ENV/);
  assert.equal(VERSION, readFileSync(`${packageRoot}/package.json`, 'utf8').match(/"version": "([^"]+)"/)[1]);
});

test('the committed reusable workflow matches the renderer', () => {
  assert.equal(readFileSync(reusableFile, 'utf8'), renderReusable());
});

test('no account name or credential is hardcoded in source', () => {
  const files = [
    `${packageRoot}/bin/mention-agent.mjs`,
    ...readdirSync(`${packageRoot}/lib`).map((name) => `${packageRoot}/lib/${name}`),
    ...readdirSync(`${packageRoot}/scripts`).map((name) => `${packageRoot}/scripts/${name}`),
  ];
  for (const file of files) {
    const text = readFileSync(file, 'utf8');
    assert.doesNotMatch(text, /faetschi/i, `hardcoded account name in ${file}`);
    assert.doesNotMatch(text, /github_pat_|ghp_[A-Za-z0-9]{20,}/, `hardcoded token in ${file}`);
  }
});

test('the hosting repository is derived from package metadata', () => {
  assert.equal(REPOSITORY, 'faetschi-bot/faetschi-bot-utils');
  assert.equal(config().workflow.reusableRepo, REPOSITORY);
  assert.doesNotMatch(renderReusable(), /faetschi/i);
});

test('--provider switches the default env, secret, and model', () => {
  const chosen = buildConfig({ flags: { mention: '@example-bot', provider: 'openai' } });
  assert.equal(chosen.provider.env, 'OPENAI_API_KEY');
  assert.equal(chosen.provider.secret, 'OPENAI_API_KEY');
  assert.equal(chosen.model, 'openai/gpt-5.6-sol');
});

test('update --provider switches defaults even when a config exists', () => {
  const existing = buildConfig({ flags: { mention: '@example-bot' } });
  assert.equal(existing.provider.env, 'OPENCODE_API_KEY');
  const updated = buildConfig({ existing, flags: { provider: 'anthropic' } });
  assert.equal(updated.provider.env, 'ANTHROPIC_API_KEY');
  assert.equal(updated.model, 'anthropic/claude-sonnet-4-5');
});

test('an unlisted provider works through explicit env/secret/model', () => {
  const custom = buildConfig({
    flags: {
      mention: '@example-bot',
      provider: 'acme',
      providerEnv: 'ACME_API_KEY',
      providerSecret: 'ACME_KEY',
      model: 'acme/rocket-1',
    },
  });
  assert.equal(custom.provider.env, 'ACME_API_KEY');
  assert.equal(custom.provider.secret, 'ACME_KEY');
  assert.equal(custom.model, 'acme/rocket-1');

  const caller = renderCaller(custom);
  assert.match(caller, /provider-env: "ACME_API_KEY"/);
  assert.match(caller, /provider-key: \$\{\{ secrets\.ACME_KEY \}\}/);
  assert.match(caller, /model: "acme\/rocket-1"/);
  assert.ok(renderReusable().includes('PROVIDER_ENV: ${{ inputs.provider-env }}'));
});

test('an unknown provider without explicit env/secret/model is rejected', () => {
  assert.throws(
    () => buildConfig({ flags: { mention: '@example-bot', provider: 'acme' } }),
    (error) => error instanceof ConfigError && /unknown provider/.test(error.message),
  );
});

test('workflow refs are immutable release tags and legacy v1 migrates on update', () => {
  const legacy = buildConfig({
    existing: { mention: '@example-bot', workflow: { ref: 'mention-agent-v1' } },
    flags: { mention: '@example-bot' },
  });
  assert.equal(legacy.workflow.ref, 'mention-agent-v0.1.0');

  const problems = validateConfig(buildConfig({
    flags: { mention: '@example-bot', ref: 'mention-agent-v1' },
  }));
  assert.ok(problems.some((message) => /exact release tag/.test(message)));
});

test('login validation rejects a trailing hyphen', () => {
  const problems = validateConfig(config({ allowUsers: ['bad-'] }));
  assert.ok(problems.some((message) => /not a valid GitHub login/.test(message)));
});

test('comment-only is the default; --allow-writes persists git credentials', () => {
  assert.match(renderStandalone(config()), /persist-credentials: false/);
  assert.match(renderStandalone(config({ allowWrites: true })), /persist-credentials: true/);
  assert.match(renderCaller(config({ allowWrites: true })), /allow-writes: true/);
  assert.match(renderCaller(config()), /allow-writes: false/);
});

test('the security checklist names the token scope and the safe default', () => {
  const commentOnly = securityChecklist(config()).join('\n');
  assert.match(commentOnly, /fine-grained token scoped to THIS repository/);
  assert.match(commentOnly, /comment-only/);
  const writes = securityChecklist(config({ allowWrites: true })).join('\n');
  assert.match(writes, /Writes are enabled/);
});

test('a restricted agent is injected by default', () => {
  const caller = renderCaller(config());
  assert.match(caller, /agent: "mention-agent"/);
  assert.match(caller, /restrict-agent: true/);

  const yaml = renderStandalone(config());
  assert.match(yaml, /name: Constrain the agent/);
  assert.match(yaml, /OPENCODE_CONFIG=\$CONFIG_PATH/);
  assert.ok(yaml.includes('"default_agent":"mention-agent"'), 'injects the restricted default agent');
  assert.ok(yaml.includes('"edit","resource":"*","effect":"deny"'), 'comment-only denies edits');
  assert.ok(yaml.includes('"edit","resource":"*","effect":"allow"'), 'the writes variant allows edits');
  assert.match(yaml, /if \[ "\$ALLOW_EDITS" = "true" \]; then/);

  const writes = renderStandalone(config({ allowWrites: true }));
  assert.ok(writes.includes('"action":"shell","resource":"npm test *"'), 'writes allow test commands');
  assert.ok(writes.includes('"action":"shell","resource":"cargo build *"'), 'writes allow build commands');
});

test('--no-restrict-agent omits the constraint and keeps the configured agent', () => {
  const flags = { restrictAgent: false, agent: 'build' };
  const yaml = renderStandalone(config(flags));
  assert.doesNotMatch(yaml, /Constrain the agent/);
  assert.match(yaml, /agent: "build"/);
  assert.match(renderCaller(config(flags)), /restrict-agent: false/);
});

test('writeEnvironment forces a standalone workflow with the environment gate', () => {
  const cfg = config({ allowWrites: true, writeEnvironment: 'mention-agent-writes' });
  assert.equal(wantsStandalone(cfg), true);
  const yaml = renderStandalone(cfg);
  assert.match(yaml, /environment:/);
  assert.match(yaml, /name: "mention-agent-writes"/);
  assert.match(yaml, /persist-credentials: true/);
});

test('writeEnvironment without allowWrites is rejected', () => {
  const problems = validateConfig(config({ writeEnvironment: 'mention-agent-writes' }));
  assert.ok(problems.some((message) => /writeEnvironment requires/.test(message)));
});

test('the checklist explains the write environment when set', () => {
  const items = securityChecklist(config({ allowWrites: true, writeEnvironment: 'mention-agent-writes' })).join('\n');
  assert.match(items, /Create environment "mention-agent-writes" with required reviewers/);
  const ungated = securityChecklist(config({ allowWrites: true })).join('\n');
  assert.match(ungated, /not environment-gated/);
});
