// session-search OpenCode plugin. Generated by `session-search install`, which
// substitutes __SESSION_SEARCH_BIN__ (and optionally __SESSION_SEARCH_CACHE__).
//
// It auto-registers the MCP server (no config edit needed), adds a /history
// command, and refreshes the index after a session settles.
import { spawnSync } from 'node:child_process';

const CLI = '__SESSION_SEARCH_BIN__';
const CACHE = '__SESSION_SEARCH_CACHE__';

export default {
  id: 'session-search',
  async setup(ctx) {
    const cacheArgs = CACHE ? ['--cache', CACHE] : [];

    await ctx.mcp.transform((editor) => {
      editor.set('session_search', {
        type: 'local',
        command: [process.execPath, CLI, 'mcp', ...cacheArgs],
        codemode: false,
        environment: CACHE ? { SESSION_SEARCH_CACHE: CACHE } : {},
      });
    });

    await ctx.command.transform((editor) => {
      editor.add({
        name: 'history',
        description: 'Search local coding-agent session history',
        execute: async ({ sessionID, prompt, delivery }) => {
          const result = spawnSync(process.execPath, [CLI, 'search', prompt.text, '--json', ...cacheArgs], {
            encoding: 'utf8',
          });
          await ctx.session.prompt({
            sessionID,
            text: result.stdout || result.stderr || '(no output)',
            delivery,
          });
        },
      });
    });

    const controller = new AbortController();
    let timer;
    void (async () => {
      for await (const event of ctx.event.subscribe({ signal: controller.signal })) {
        const idle = event.type === 'session.status' && event.data?.status?.type === 'idle';
        if (!idle) continue;
        clearTimeout(timer);
        timer = setTimeout(() => {
          spawnSync(process.execPath, [CLI, 'index', '--project', ctx.location.directory, ...cacheArgs], {
            encoding: 'utf8',
          });
        }, 1500);
      }
    })();

    return () => {
      controller.abort();
      clearTimeout(timer);
    };
  },
};
